Don't stack black mask and salve amulet
oldschoolgg/oldschoolbot pull request #2148
Opened 2021-06-21 09:48 UTC by themrrobert

### Description:
Black mask and salve i don't stack in the game, they shouldn't stack in the bot, it would be too op.

### Changes:
Black mask checks only roll if salve boost is not already applied.

### Other checks:
-   [x] I have tested all my changes thoroughly.

2021-06-21 23:09 UTC, gc requested changes

2021-06-21 23:09 UTC, gc commented on src/commands/Minion/k.ts
> +					msg.author.hasItemEquippedOrInBank('Black mask (i)'))
this `||` isnt needed.

2021-06-21 23:09 UTC, gc commented on src/commands/Minion/k.ts
> +		const salveBoost = boosts.join('').toLowerCase().includes('salve amulet');
this is some spaghetti. but im okay with it

2021-06-22 08:53 UTC, themrrobert commented on src/commands/Minion/k.ts
> +					msg.author.hasItemEquippedOrInBank('Black mask (i)'))
We discussed this in chat.

2021-06-23 17:16 UTC, merged