Favalch in alch
oldschoolgg/oldschoolbot pull request #2378
Opened 2021-07-18 11:59 UTC by Lilylicious

### Description:

Adds favalch to alch trips with no item provided.

### Other checks:

-   [X] I have tested all my changes thoroughly.

2021-07-18 17:42 UTC, gc requested changes

2021-07-18 17:42 UTC, gc commented on src/commands/Minion/alch.ts
> +			.sort((a, b) => b.highalch - a.highalch);
this is duplicated in the agility alching isnt it? might be better to put this in a utility function if so, e.g. `getUsersFavAlchs` or something.

2021-07-18 18:07 UTC, Lilylicious commented
Updated alch/laps to use a get function in the User extendable

2021-07-20 00:30 UTC, gc requested changes

2021-07-20 00:30 UTC, gc commented on src/lib/types/Augments.d.ts
> +		getUserFavAlchs(): Item[];
if this is going to be an extendable, then it shouldnt have `User` in the name, my suggestion wasnt for an extendable but just a regular function taking the user as an arg.

2021-07-31 07:00 UTC, merged