add driftnet
oldschoolgg/oldschoolbot pull request #2490
Opened 2021-08-01 00:07 UTC by Lajnux

### Description:

added the hunter/fishing activity drift net fishing

### Changes:

added the hunter/fishing activity drift net fishing
Balanced rates and items needed

### Other checks:

-   [X] I have tested all my changes thoroughly.

2021-08-01 06:39 UTC, gc requested changes

2021-08-01 06:39 UTC, gc commented on src/commands/Minion/driftnet.ts
> +		if (!bankHasItem(userBank.bank, itemID('Drift net'), quantity)) {
use `userBank.has()`

2021-08-01 06:39 UTC, gc commented on src/commands/Minion/driftnet.ts
> +			!msg.author.hasItemEquippedAnywhere('Graceful legs')
You can check these in 1 line, as an array.

2021-08-01 06:39 UTC, gc commented on src/tasks/minions/HunterActivity/driftNetActivity.ts
> +const FishBonusLoot = [
camelcase

2021-08-02 12:17 UTC, gc requested changes

2021-08-02 12:17 UTC, gc commented on src/commands/Minion/driftnet.ts
> +			return msg.channel.send('You need Graceful top,legs and gloves equipped to do Drift net fishing.');
missing a space here

2021-08-02 12:17 UTC, gc commented on src/commands/Minion/driftnet.ts
> +				`You need ${quantity}x Drift net for the whole trip, try a lower trip lengthor make/buy more Drift net.`
missing a space here

2021-08-02 12:17 UTC, gc commented on src/tasks/minions/HunterActivity/driftNetActivity.ts
> +		await user.addItemsToBank(loot.values(), true);
ii dont think you need loot.values() here, just loot.

2021-08-06 22:52 UTC, themrrobert approved these changes

2021-08-07 20:38 UTC, merged