Monkey rumble
oldschoolgg/oldschoolbot pull request #2810
Opened 2021-09-08 14:04 UTC by gc

### Description:

### Changes:

### Other checks:

-   [ ] I have tested all my changes thoroughly.

2021-09-09 13:16 UTC, imgidedin commented on src/commands/Minion/mmmr.ts
> +	async buy(msg: KlasaMessage, [input = '']: [string]) {
Missing `@requiresMinion` decorator

2021-09-09 13:25 UTC, imgidedin commented on src/commands/Minion/mmmr.ts
> +		const buyable = buyables.find(i => stringMatches(input, i.item.name));
Buyables is not using the `buyables.aliases` defined.

2021-09-09 13:27 UTC, imgidedin commented on src/commands/Minion/mmmr.ts
> +		});
Still has the barbarian assault information

2021-09-09 13:38 UTC, imgidedin commented on src/tasks/minions/minigames/monkeyRumbleActivity.ts
> +			);
This seems unnecessary, as for the return message, the first element is sent. Maybe do `if(files.length === 0) files.push(...);`. That will save time generating _n_ amount of chatheads that will never be used.

2021-09-10 09:31 UTC, themrrobert requested changes

2021-09-10 09:35 UTC, themrrobert commented on src/commands/Minion/mmmr.ts
> +			monkeysToFight.push(getRandomMonkey(monkeysToFight, chanceOfSpecial));
Actually this looks like it's not actually excluding all previously fought monkeys like I initially thought. So you can disregard

2021-09-10 12:07 UTC, merged