Show Sac Value
oldschoolgg/oldschoolbot pull request #3269
Opened 2021-12-11 01:50 UTC by LuxrayElite

### Description:

solves issue #1334

Added visible sac value without sacrificing an item

### Changes:

Used a Variable of SacVal as a constant instead of making multiple calls (Fixed Value)
Returns full-length sac value and shorthand on no item provided eg  1,031,252,102 (1.03b)

### Other checks:

-   [ x] I have tested all my changes thoroughly.

2021-12-11 13:37 UTC, themrrobert requested changes

2021-12-11 13:37 UTC, themrrobert commented on src/commands/Minion/sacrifice.ts
> +		const SacVal = await msg.author.settings.get(UserSettings.SacrificedValue);
SacVal should be `sacVal` to match the style.

2021-12-11 13:37 UTC, themrrobert commented on src/commands/Minion/sacrifice.ts
> +				`No items were provided. \nYour current sacrificed value is: ${SacVal.toLocaleString()} (${Util.toKMB(
No space needed before `\n`

2021-12-11 13:53 UTC, LuxrayElite commented
Suggested chaged by themrrobert have been made

2022-01-03 16:06 UTC, gc requested changes

2022-01-03 16:06 UTC, gc commented on src/commands/Minion/sacrifice.ts
> +		const sacVal = await msg.author.settings.get(UserSettings.SacrificedValue);
no `await`, `settings.get` doesnt return a promise.

2022-01-03 16:22 UTC, merged