Add Minnows
oldschoolgg/oldschoolbot pull request #3361
Opened 2021-12-28 20:00 UTC by TastyPumPum

Add the fishing of minnows and the buying of raw sharks, anglers has to be equipped to fish minnows as you need the outfit in game. Made it so crystal harpoon doesn't boost it. Rates were obtained from the osrs wiki.

-   [ ] I have tested all my changes thoroughly.

2021-12-29 19:44 UTC, LuxrayElite commented
Fun Collab of balancing 🤣

2022-01-02 11:53 UTC, gc requested changes
looks alright, is it tested by testers?

2022-01-02 11:53 UTC, gc commented on src/commands/Minion/fish.ts
> +		) {
use `[].some` instead of this.

2022-01-02 15:07 UTC, TastyPumPum commented
> looks alright, is it tested by testers?

It has been tested throughly by myself, lux has helped test and code it. I can get it tested extensively in ironcord.

2022-01-04 23:14 UTC, TastyPumPum commented
> looks alright, is it tested by testers?

The scaled time per fish has now been done on a curve basis using the information provide on the wiki, this has been capped at the scale for 99 due to BSO levelling. The cap can be removed if needed. 

This has been tested a lot by myself, with others testing and helping.

2022-01-08 18:17 UTC, merged