Raid clue scroll marker
oldschoolgg/oldschoolbot pull request #3505
Opened 2022-02-03 00:22 UTC by POKEBLOX6

I added a clue scroll emoji and now when a user receives a clue scroll from a raid it will pop up with the emoji except when there is an important drop (as the user is most likely going to be more excited over the purple)

![image](https://user-images.githubusercontent.com/42723789/152259955-1dbd9a62-8273-4816-b9ae-94ff9e2b6f07.png)

-   [X] I have tested all my changes thoroughly.

2022-09-12 11:33 UTC, Lajnux commented on src/lib/constants.ts
> +	Clue = '<:Clue_scroll:365003979840552960>',
```suggestion
	Clue = '<:clue_scroll:365003979840552960>',
```
small letter for consistency.

2022-09-12 11:34 UTC, Lajnux commented
Are you planning to resolve the conflict? looks good to merge if resolved.

2022-09-12 17:10 UTC, ianfights commented
> Are you planning to resolve the conflict? looks good to merge if resolved.

Yep I'll go ahead and make those changes once I get home

2022-09-13 13:49 UTC, ianfights commented
Conflicts should be fixed

2022-09-13 14:02 UTC, Lajnux commented
run a yarn lint and it should all be good.

2022-09-13 17:41 UTC, ianfights commented
Adressed the issue

2022-10-18 12:24 UTC, gc requested changes

2022-10-18 12:24 UTC, gc commented on src/tasks/minions/minigames/raidsActivity.ts
> +			const clue = items.some(([item]) => item.name.toLowerCase().includes('clue scroll'));
`if (ClueTiers.some(t => items.has(t.scrollID))` (rather than arbitrary string checking)

2023-02-07 22:23 UTC, osrsjobbo commented on src/tasks/minions/minigames/raidsActivity.ts
> +			const clue = items.some(([item]) => item.name.toLowerCase().includes('clue scroll'));
Done

2024-11-23 06:22 UTC, closed without merging