Thieving Stalls
oldschoolgg/oldschoolbot pull request #3853
Opened 2022-05-02 08:09 UTC by Lajnux

### Description:

Added stalls as stealable objects and balanced rates to be similar to in game along with requirements.

### Changes:

New Stalls as stealable objects

### Other checks:

-   [X] I have tested all my changes thoroughly.

2022-05-30 13:33 UTC, gc requested changes
1. the 1 comment i left
2. we should make it into a centralized `steal` slash command, which accepts any npc/stall.

After these 2 things, and assuming its tested and the rates are measured/balanced, this looks good to merge.

2022-05-30 13:33 UTC, gc commented on src/commands/Minion/pickpocket.ts
> +			: (<Stall>stealable).respawnTime;
we dont do stuff like this anywhere. you should convey this in the type itself. rough example:
```ts
type Stealable = { type: 'pickpocket' | 'stall' } & (PickpocketNPC | Stall);
type Pickpocketable {
type: 'pickpocket',
customTickRate: 1,
}
type Stall {
type: 'stall'
}

const timeToTheft = stealable.type === 'pickpocket' ? stealable.customTickrate : stealable.whatever;
```

2022-08-01 09:50 UTC, gc requested changes
also have you checked xp rates of everything?

2022-08-01 09:50 UTC, gc commented on src/lib/skilling/skills/thieving/stealables.ts
> +		alias: ['Baker stall', 'Baker', 'Bakers stall'],
aliases, in the bot and osjs, we always have them all lowercase

2022-08-01 09:50 UTC, gc commented on src/lib/skilling/skills/thieving/stealables.ts
> +	alias?: string[];
`aliases`

2022-08-01 18:03 UTC, Lajnux commented
> also have you checked xp rates of everything?

yupp, it's all good and fair and tested, had a extra test up now today aswell.

2022-08-07 16:51 UTC, gc requested changes

2022-08-07 16:51 UTC, gc commented on src/mahoji/commands/steal.ts
> +			return 'This NPC/Stall is not working as intended, report it.';
dont do this - use `logError` so we can actually know if something like this happens

2022-08-07 17:23 UTC, merged