[Leagues-BSO] Fixes "Unlock all Slayer rewards" bug for leagues
oldschoolgg/oldschoolbot pull request #4168
Opened 2022-07-12 21:02 UTC by themrrobert

### Description:

The enum has a dummy entry to take the place of the '0th' element, as well as includes non-unlockables, such as the herb sack and slayer ring. I probably should have named it `SlayerRewardsEnum` but oh well. 

### Changes:

- Pre-filters a list of just the unlockable Slayer rewards so this doesn't have to be computed every time.
- Updates the task to use the new list for the length check

### Other checks:

-   [x] I have tested all my changes thoroughly.

2022-07-13 02:50 UTC, gc commented
```ts
export enum SlayerTaskUnlocksEnum {
	Dummy = 0,
```
disaster

2022-07-13 09:04 UTC, themrrobert commented
> ```ts
> export enum SlayerTaskUnlocksEnum {
> 	Dummy = 0,
> ```
> 
> disaster


Yea definitely wouldn't do that today, in fact, I can just pull that out and set GargoyleSmasher to 1, but hat's not even enabled either. And even if neither of those were there, the code still wouldn't work, because not all of those are unlocks, the Enum isn't named well either

2022-07-14 05:46 UTC, gc requested changes

2022-07-14 05:46 UTC, gc commented on src/lib/slayer/slayerUnlocks.ts
> -	// Unlock superiors
these should be osb changes

2022-07-19 09:16 UTC, merged