Daeyalt Essence - Runecrafting/Mining
oldschoolgg/oldschoolbot pull request #4218
Opened 2022-07-20 17:28 UTC by TastyPumPum

Checks for the relevant skill levels and quest points before allowing you to mine Daeyalt Shards.
Adds the mining of daeyalt shards to gather daeyalt essence (auto banks the essence instead of the shards as that's their only purpose)
Adds a boolean optional command on the runecrafting command to use daeyalt essence at a 50% increased xp rate. (doesn't work on blood/soul runes)
If the boolean is not selected it defaults to false.

Closes #1017

-   [x] I have tested all my changes thoroughly.

2022-07-23 16:21 UTC, themrrobert requested changes

2022-07-25 20:16 UTC, TastyPumPum commented on src/mahoji/commands/mine.ts
> +			if (user.QP < 16) {
Just changed it to 125 which matches our requirement of creating a blisterwood flail (which requires the same quest)

2022-08-01 07:59 UTC, gc commented
Has this been tested by testers?

2022-08-01 08:04 UTC, TastyPumPum commented
> Has this been tested by testers?

Yeah it got tested in the testing servers, and any changes requested got updated

2022-09-02 09:14 UTC, closed without merging