Sell golden tenches for molch pearls
oldschoolgg/oldschoolbot pull request #4232
Opened 2022-07-21 22:26 UTC by TastyPumPum

Adds the ability to sell golden tenches for molch pearls, this was lost when moved to mahoji.
Closes #3999

-   [x] I have tested all my changes thoroughly.

2022-07-22 02:37 UTC, gc requested changes
What if someone tries to sell a tbow and a golden tench at the same time? do the same thing we do for mole claws

2022-07-22 13:31 UTC, gc requested changes
![963354987835039785](https://user-images.githubusercontent.com/30398469/180449625-466ed976-4e33-4958-8137-fda9e46f4d9c.png)

2022-07-23 16:27 UTC, TastyPumPum commented
> ![963354987835039785](https://user-images.githubusercontent.com/30398469/180449625-466ed976-4e33-4958-8137-fda9e46f4d9c.png)

I believe I have done this how you wanted now, if I haven't some further guidance would be appreciated instead of an emoji. Tested with trying to sell multiple items and seems to mirror the mole claws/skins.

2022-07-24 23:41 UTC, gc requested changes
The hamstare was because of blatantly untested code (which was fixed)

2022-07-24 23:41 UTC, gc commented on src/mahoji/commands/sell.ts
> +			}
`loot.add(tenchBank.amount() * 100)` ?

2022-07-25 16:20 UTC, TastyPumPum commented
Sorry I should have marked it as a draft at that point, I was on mobile and done them changes so it would prompt me on pc, I didn't expect you to come back to it so quick without me replying or anything.

2022-08-01 09:33 UTC, merged