Make Wintertodt messages consistent with minionKill
oldschoolgg/oldschoolbot pull request #4889
Opened 2023-01-28 20:10 UTC by osrsjobbo

### Description:

Fixes issues described in #4887. I took inspiration from minionKill.ts to try create a consistent experience. 

![image](https://user-images.githubusercontent.com/123830708/215288713-e4adf7c6-ead3-4187-90fc-c30c8f0a2a4b.png)

### Changes:

Use line breaks & bold to make more consistent with other areas of the bot. 

### Other checks:

-   [X] I have tested all my changes thoroughly.

2023-02-04 10:31 UTC, gc requested changes

2023-02-04 10:31 UTC, gc commented on src/mahoji/lib/abstracted_commands/wintertodtCommand.ts
> +		messages.push(`**Boosts: ** ${wcBoost.toFixed(2)}%  for Woodcutting level\n`);
this string is written weirdly, you're making a space bold - and theres a double space

2023-02-04 20:33 UTC, osrsjobbo commented
@gc Done & tested

2023-02-13 12:36 UTC, gc commented
Failing tests

2023-02-13 21:11 UTC, osrsjobbo commented
Fixed

2023-02-18 06:57 UTC, merged