Can use divine rune pouch in place of rune pouch in inferno
oldschoolgg/oldschoolbot pull request #4931
Opened 2023-02-07 12:40 UTC by Sturminator3

### Can use divine rune pouch in place of rune pouch in inferno

Closes #4927

### Changes:

### Other checks:

-   [x] I have tested all my changes thoroughly.

2023-02-07 13:28 UTC, LuxrayElite commented
It would probably be best to implement similar code to the tob fix 

https://github.com/oldschoolgg/oldschoolbot/blob/e4b5198ab05a1acee4f5974c97ca5a2481572458/src/mahoji/lib/abstracted_commands/tobCommand.ts#L106-L109

Magna also prefers using for of instead of forEach due to speed :)

2023-02-07 13:41 UTC, Sturminator3 commented
> 

Sounds good I can make those changes!

2023-02-07 14:17 UTC, Sturminator3 commented
@LuxrayElite When I add that return statement im getting a bunch of compilation errors in my file. Do you know if there is some sort of setting I need for it?

`return [true, '${user.usernameOrMention}'s doesn't have a Rune pouch.'];`

2023-02-07 15:24 UTC, LuxrayElite commented
Saw the comment in gitlogs :P, glad you figured it out.

Much tidier now :) good job on the first PR

2023-02-07 15:27 UTC, LuxrayElite commented
Id probably use the old message error message as well just cause the one from ToB pings the user 👍 

![image](https://user-images.githubusercontent.com/12814878/217288170-e36d6570-a7b3-4ade-8f19-753ecf4b87c6.png)

2023-02-07 17:26 UTC, Sturminator3 commented
@LuxrayElite Changes have been pushed!

2023-02-13 12:52 UTC, gc requested changes

2023-02-13 12:52 UTC, gc commented on src/mahoji/lib/abstracted_commands/infernoCommand.ts
> +			itemRequirementNames.push(itemNameFromID(item) as string);
this typecast shouldnt be needed.

2023-02-13 12:52 UTC, gc commented on src/mahoji/lib/abstracted_commands/infernoCommand.ts
> +		return `To do the Inferno, you need one of these items: ${itemRequirementNames.join(', ')}.`;
this `itemRequirementNames` is a bit odd. Try just `itemRequirements.map(itemNameFromID).join(", ")`

2023-02-13 13:30 UTC, Sturminator3 commented
@gc PR has been updated with your changes

2023-02-13 21:06 UTC, osrsjobbo commented
Ready for review, tests green

2023-02-18 05:53 UTC, merged