add last man standing fun simulation command
oldschoolgg/oldschoolbot pull request #499
Opened 2020-08-10 19:29 UTC by Alexsuperfly

### Description:

creates a last man standing command in the OSRS_Fun directory to simulate a game of last man standing in the same manner that skyra does it with its hunger games command.

This is fully adopted from their implementation and just adjusted to be themed with OSRS and some functionality was dropped since OSBot doesnt have all the utility already built in that Skyra does

### Changes:

-   [] I have tested all my changes thoroughly.

2020-09-01 15:11 UTC, gc requested changes
a few things: youre adding lms wins/points as minigames, which makes no sense, it should be just LMS, and since this is just simulation it should be stateless and have no settings changing. `LastmanStandingUsage` should be put somewhere else, its not a command. and after removing that, LMS doesnt need its own folder. it also seems like the messages are duplicated in these 2 files, shouldnt they be in only 1?

2020-09-01 22:26 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1} runs into upstairs in a building and hides.',
'{1} runs into a building and hides upstairs.',

2020-09-01 22:27 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1} takes a handful of Morrigan Javelins.',
'{1} takes a handful of Morrigan's Javelins.',

2020-09-01 22:27 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1} runs into upstairs in a building and hides.',
'{1} runs into a building and hides upstairs.',

2020-09-01 22:27 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1} grabs a Vesta longsword.',
'{1} grabs a Vesta's longsword.',

2020-09-01 22:28 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1} finds a supply box full of Granite mauls & supplies.',
'{1} finds a box full of supplies and a Granite maul.',

2020-09-01 22:29 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	"{1} grabs a Stamina potion while {2} gets Ahrim's robes.",
"{1} grabs a Stamina potion while {2} finds a set of Ahrim's robes.",

2020-09-01 22:29 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1} trips over while running to a building, {2} picks them up, they run off together.'
'{1} trips over while running to a building, {2} picks them up and they run off together.'

2020-09-01 22:30 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	"{1K} DDS specs {2D} while they're purchasing supplies.",
"{1K} fatally DDS specs {2D} while they're purchasing supplies.",

2020-09-01 22:32 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1} and {2} work together for now.',
'{1} and {2} work together, for now...',

2020-09-01 22:35 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1K} repeatedly stabs {2D} to death with Draggon dagger.'
'{1D} Talks about how good they are while fighting {2K} and is promptly stacked out by {2K}',

2020-09-01 22:35 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1K} repeatedly stabs {2D} to death with Draggon dagger.'
as an addition

2020-09-01 22:36 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	"{1K} throws a Morrigan Javelin into {2D}'s head.",
"{1K} throws a Morrigan's Javelin into {2D}'s head.",

2020-09-01 22:36 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1D} cannot handle the circumstances and runs in the fog.',
'{1D} cannot handle the circumstances and runs off into the fog.',

2020-09-01 22:37 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1K} kills {2D} as they try to run.',
'{1K} kills {2D} as they try to run away.',

2020-09-01 22:38 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1D}, {2D}, {3D}, and {4D} form a suicide pact, and run in the fog.',
'{1D}, {2D}, {3D}, and {4D} form a suicide pact, and run off into the fog.',

2020-09-01 22:39 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1} trips over while running from the fog, {2} picks them up, they run off together.',
'{1} trips over while running from the fog, {2} picks them up and they run off together.',

2020-09-01 22:40 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1D} unknowingly eats cavada berries.',
'{1D} unknowingly eats cavada berries and dies.',

2020-09-01 22:42 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1D} accidently detonates a land mine while trying to arm it.',
'{1D} accidentally detonates a Chinchompa while trying to pet it.',

2020-09-01 22:42 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1D} accidently detonates a land mine while trying to arm it.',
There are no land mines in runescape :)

2020-09-01 22:43 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	"{1K} shoots a poisonous blow dart into {2D}'s neck, slowly killing them.",
"{1K} shoots a poisonous bronze dart into {2D}'s neck, slowly killing them.",

2020-09-03 16:02 UTC, osrsolympus commented
Perhaps a “**User** is found to be using an auto-prayer client and is banned mid game“ line for the lols

2020-09-03 16:10 UTC, TwiceUponATaco requested changes
Changed unknown sponsor to random chest to fit the LMS theme better

2020-09-03 16:10 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1} receives a Dragon hatchet from an unknown sponsor.',
'{1} receives a Dragon hatchet from a random chest.',

2020-09-03 16:10 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1} receives a combat potion from an unknown sponsor.',
'{1} receives a combat potion from a random chest.',

2020-09-03 16:10 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1} receives a bag of potions from an unknown sponsor.',
'{1} receives a bag of potions from a random chest.',

2020-09-03 16:10 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1} receives food from an unknown sponsor.',
'{1} receives food from a random chest.',

2020-09-03 16:10 UTC, TwiceUponATaco commented on src/lib/LastManStandingUsage.ts
> +	'{1} receives a chinchompa from an unknown sponsor.',
'{1} receives a chinchompa from a random chest.',

2020-09-03 16:13 UTC, TwiceUponATaco commented
Suggested Lines:
1 trips over a chinchompa while running away from 2, blowing themself up.
1 trips over a chinchompa while running away from 2, blowing them both up.

2020-09-04 16:07 UTC, merged