Strung Rabbit Foot necklace
oldschoolgg/oldschoolbot pull request #5017
Opened 2023-03-19 18:44 UTC by TastyPumPum

Adds the crafting of the strung rabbit foot necklace. 

Adds the relevant effect onto the woodcutting activity, will have to be equipped for it to take place, as some people might prefer the seeds instead

-   [x] I have tested all my changes thoroughly.

2023-03-19 18:56 UTC, TastyPumPum commented on src/lib/skilling/skills/hunter/birdHouseTrapping.ts
> +	strungRabbitFootTable: LootTable;
Theres probably an easier way to do this, any advice would be appreciated

2023-03-19 23:06 UTC, ColossalSeagull commented
Does this affect birdhouses as well? Since it does affect egg nests on bh runs in game as well. 
![image](https://user-images.githubusercontent.com/96855950/226215389-ae616b3a-71ee-4400-a665-b67b5c586135.png)

2023-03-19 23:07 UTC, TastyPumPum commented
Yes I mentioned that in my original post

2023-03-24 05:03 UTC, gc requested changes

2023-03-24 05:03 UTC, gc commented on src/lib/skilling/skills/crafting/craftables/misc.ts
> +		inputItems: new Bank({ 'Ball of wool': 1, 'Rabbit foot': 1 }),
Switch to `.add`

2023-03-24 05:03 UTC, gc commented on src/tasks/minions/HunterActivity/birdhouseActivity.ts
> +				str += "\nYour strung rabbit foot necklace increases the chance of recieving bird's eggs and rings.";
typo

2023-03-24 05:03 UTC, gc commented on src/tasks/minions/woodcuttingActivity.ts
> +			str += "\nYour strung rabbit foot necklace increases the chance of recieving bird's eggs and rings.";
typo

2023-03-27 16:06 UTC, TastyPumPum commented on src/lib/skilling/skills/hunter/birdHouseTrapping.ts
> +			.tertiary(3, 'Feather', [10, 100]),
Not sure if I've done it how you wanted it, but made some changes to it, let me know if it needs changing and if you could give further guidance would be appreciated.

2023-04-27 15:20 UTC, merged