Allow Patron users to disable daily DMs
oldschoolgg/oldschoolbot pull request #5267
Opened 2023-08-15 17:54 UTC by TastyPumPum

Allows users to disable daily dms if they so wish.

- [ ] I have tested all my changes thoroughly.

2023-08-16 10:57 UTC, TURB042O commented
_Future Proposal posted by @mylife212 in https://github.com/oldschoolgg/oldschoolbot/issues/5263

2023-08-18 00:48 UTC, gc requested changes

2023-08-18 00:48 UTC, gc commented on src/lib/tickers.ts
> +				if (row.bitfield === 31) continue;
`if (row.bitfield === 31) continue;` i dont really understand this, isnt bitfield an array and this would throw an error?

2023-09-22 17:09 UTC, gc commented
Did you manually test the sql?

2023-09-22 17:11 UTC, TastyPumPum commented
> Did you manually test the sql?

No I'm not too sure to test really, that's why I've left the label there for now, if you can assist with testing or want to take over this PR feel free

2024-11-15 09:27 UTC, closed without merging