Hunter rumours v2
oldschoolgg/oldschoolbot pull request #6077
Opened 2024-10-01 09:13 UTC by DaughtersOfNyx

### Description:

This PR adds the following:

 - Hunter Rumours, accessible via /rumours start
 - A Rumour blocklist, accessible via /rumours manage
 - Checking Rumour count via /rumours count
 - Rumour Collection Log, including 5 items and a pet
 
 - 7 New Hunter Creatures (Embertailed Jerboa, Sunlight Moth, Moonlight Moth, Sunlight Antelope, Moonlight Antelope, Pyre Fox,  Tecu Salamander)
 - 2 New Buyables (Mixed Hide Base & Jaguar Fur)
 - 11 New Createable Items (Mixed Hide Armor, Quetzal Whistles and hunter's spear and sunlight crossbow)
 - 9 New Cookable and Eatable hunter meats, with the higher tiers having PVM bonuses
 - 4 New Openable Hunter Sacks, one for each tier
 - 2 New Fletchable Items (from antelope antlers)
 - Hunter Outfit Mod boosting catch chance

### Changes: (Backend Stuff)

- Added rumour stats and blocklist to the Schema
- Added a Rumour command + subcommands and Activity
- Added an optional field called "rumoursRequired" to cookables to allow for the rumour requirement for cooking hunter meats to work, this shouldn't (and doesn't from my testing) break anything existing
- Added an optional array named "tier" to hunter creatures to specify what tier/s of rumour they can be assigned for

### Other checks:

- [x] I have tested all my changes thoroughly. (2 Rounds of testing in the testing discord, alongside extensive testing privately by myself and a friend.

2024-10-01 09:25 UTC, DaughtersOfNyx commented
@ellipsis-dev review this PR

2024-10-01 09:27 UTC, DaughtersOfNyx commented
I don't think I gave ellipsis enough information it seems a smidgeon confused

2024-10-13 01:42 UTC, gc requested changes
the gif image has been corrupted, to fix it first merge master, these 2 commands may fix it:

```
git rm --cached -r . 
git add .
```
otherwise, you could just manually put the gif there.

2024-10-13 01:54 UTC, gc requested changes
Instead of using `Record<RumorIndex, number>` for their "kc" of each rumour,  put this in src\lib\structures\Bank.ts

```ts
export class RumorTierBank extends GeneralBank<RumourOption> {
	constructor(initialBank?: GeneralBankType<RumourOption>) {
		super({ initialBank, allowedKeys: RumourOptions });
	}

	toJSON() {
		return this._bank;
	}
}
```

Now, you have a easier (and typesafe) way to add/remove/etc KCs.
```ts
const rumourTierBank = new RumorTierBank();
rumourTierBank.add('novice', 1);
```

updating:
```ts
await userStatsUpdate(user.id, { rumours: rumourTierBank.toJSON() }, {});
```

2024-10-13 01:54 UTC, gc commented on prisma/schema.prisma
> +  rumours                  Int[] @default([0, 0, 0, 0])
To prevent your PR changing all these lines, separate your addition with an empty line.

2024-10-13 01:54 UTC, gc commented on src/lib/skilling/skills/hunter/rumours/rumours.ts
> +	const blockList = (await getRumourBlockList(user.id)).rumour_blocked_ids;
Cant you just do `user.user.rumour_blocked_ids` ? the `getRumourBlockList` function seems pointless

2024-10-13 01:54 UTC, gc commented on src/lib/skilling/skills/hunter/rumours/rumours.ts
> +		const DurationAndQty = calcDurationAndQty(selectedCreature, user);
this should be camelcase

2024-10-13 01:54 UTC, gc commented on src/lib/skilling/skills/hunter/rumours/rumours.ts
> +		if (tier === 'novice' || tier === 'adept') DurationAndQty[0] += 50; //Extra 50 seconds per task for low rumour tier (creatures are more spread out)
put comments like this on the line above

2024-10-13 01:54 UTC, gc commented on src/lib/skilling/skills/hunter/rumours/rumours.ts
> +	if (dropRate === -1) {
This should probably be checking for `undefined`

2024-10-13 01:54 UTC, gc commented on src/lib/skilling/skills/hunter/rumours/rumours.ts
> +	const totalrumours = rumoursCompleted.reduce((a, b) => a + b);
this should be camelcase. Note that we have a `sumArr()` fn you could use too.

2024-10-13 01:54 UTC, gc commented on src/tasks/minions/rumourActivity.ts
> +		const newTotalrumours = rumoursCompleted.reduce((a, b) => a + b);
should be camelcase

2024-10-13 01:54 UTC, gc commented on src/lib/skilling/skills/hunter/rumours/rumourBlocks.ts
> +		const tier = RumourOptions[i].charAt(0).toUpperCase() + RumourOptions[i].slice(1);
You may want the `toTitleCase()` function here.

2024-10-13 01:55 UTC, gc commented on prisma/schema.prisma
> +  rumour_blocked_ids     Int[]     @default([0, 0, 0, 0])
I dont see why this is an array of 4 0's by default.

2024-11-23 06:22 UTC, closed without merging