Clue scrolls rebalancing
oldschoolgg/oldschoolbot pull request #6111
Opened 2024-10-11 17:02 UTC by Arodab

### Description:

Clues in OSB are completed much slower compared to OSRS. This PR updates the boosts and base clue timers to match the rates found in the [Efficient Hours Collected (EHC) spreadsheet](https://docs.google.com/spreadsheets/d/16bZ10q9aD_4vVgA1RX2ZpPVxI9pUrBcj9kICNo9obgo/edit?gid=929714382#gid=929714382)  from the _Log Hunters_ discord.

### Changes:

-Added boosts for Skull Sceptre to beginner/easy clues.
-Added boosts for Book of the Dead to hard/elite/master clues.
-Increased boosts across all items that previously boosted clues.
-Adjusted base clue times for better balance due to global boosts.
-Increased minion learning cap to 25%, because experience completing clues is arguably more important than any item.
-Removed weekend boost for clues, this is already a huge buff to clue rates, we don't need a FOMO boost on top of it.

### Other checks:

- [ ] I have tested all my changes thoroughly.

2024-10-12 08:57 UTC, gc commented
Can you post the new rates? did testers give feedback on it?

2024-10-12 14:44 UTC, Arodab commented
> Can you post the new rates? did testers give feedback on it?

New rates are very slightly lower than the ones in the spreadsheet (off by less than 1/hr):

Beginner: 50/hr
Easy: 45/hr
Medium: 30/hr
Hard: 20/hr
Elite: 10/hr
Master: 6/hr

I tested it myself, can post trips somewhere if you want, but feedback seemed mostly positive from bso-general. Some people didn't like me removing weekend boost. I still stand by it since it's a huge buff to old rates already, we don't really need another 10%, but I could put it back. Happy to nerf it a bit too if you feel it's too much, but these are the rates people get in OSRS.

2024-11-09 16:01 UTC, Arodab commented
> Most important thing for this is if testers agree with the new rates.

The only argument against these rates was clue juggling not being implemented in the bot yet. But I see you made a PR for it, so no one should disagree now.

2024-11-09 16:04 UTC, AvariceBrah commented
This obviously will never have ground in bso, safe to assume, yes?

2024-11-09 16:05 UTC, Arodab commented
> This obviously will never have ground in bso, safe to assume, yes?

I don't care about BSO at all, up to Magna.

2024-11-16 00:21 UTC, gc requested changes
Make sure to run `yarn dev` after doing the requested changes.

2024-11-16 00:21 UTC, gc commented on src/mahoji/commands/clue.ts
> +		duration *= 1 - stashBoost / 100;
Use our standard way instead: `duration = reduceNumByPercent(duration, percentage)`

2024-11-16 00:21 UTC, gc commented on src/mahoji/commands/clue.ts
> +			duration *= 1 - combatBoost / 100;
You can keep this as is (without using reduceNumByPercent), as it can be negative or positive.

2024-11-16 00:21 UTC, gc commented on src/mahoji/commands/clue.ts
> +		} clues, it'll take around ${formatDuration(duration)} to finish (${((quantity / duration) * 3600000).toFixed(1)}/hr).${
Dont use magic numbers (36000000), in this case I think you want to use `Time.Hour`.

2024-11-16 00:21 UTC, gc commented on src/mahoji/commands/clue.ts
> +		duration *= 1 - stashBoost / 100;
ACTUALLY - if this number can be negative, ignore this.

2024-11-16 02:13 UTC, merged