Adds Tokkul Shop (+tokkulshop/+tks)
oldschoolgg/oldschoolbot pull request #654
Opened 2020-09-20 01:42 UTC by kevinsmendes

### Description:

-   People have been asking for a tokkul shop so fightcaves tokkul have a use;
-   People sell items to the shop for tokkul and buy some items from the shop using tokkul;
-   The sell price considers the normal stock and the buy price considers the stock as overstocked, to avoid merching tokkul;
-   Items that have default stock of 0 can not be bought;
-   Adds the possibility to buy all the obisidian items, including the obsidian armour;
-   Requires a fight cape in the collection before the bot allows the user to interact with it.

### Changes:

-   Moved buyables and tokkulBuyables to another directory
-   Adds tokkulshop

-   [X] I have tested all my changes thoroughly.

2020-09-20 01:59 UTC, Lajnux commented on src/lib/buyables/tokkulBuyables.ts
> +		tokkulReturn: 100
Onyx bolt tips are commonly 50 in stock

2020-09-20 13:21 UTC, Alexsuperfly requested changes

2020-09-20 13:21 UTC, Alexsuperfly commented on src/commands/Minion/tokkulshop.ts
> +			!bankHasAllItemsFromBank(msg.author.collectionLog, resolveNameBank({ 'Fire cape': 1 }))
why not just actually check jad kc instead of using this round about method

2020-09-20 13:21 UTC, Alexsuperfly commented on src/lib/buyables/tokkulBuyables.ts
> +	buyable?: boolean;
instead of explicitly making a boolean for if its buyable, just look if youve defined a sell price for it

2020-09-22 15:27 UTC, gc requested changes

2020-09-22 15:27 UTC, gc commented on src/commands/Minion/tokkulshop.ts
> +				throw `I am sorry JalYt, but yo don't have enough items for that. You need **${itemString}** to sell for **${inItemString}**.`;
`you`

2020-09-22 15:27 UTC, gc commented on src/lib/buyables/tokkulBuyables.ts
> +
one item in the shop, isnt the "shop", should be named `TokkulShopItem`

2020-09-22 15:27 UTC, gc commented on src/lib/buyables/tokkulBuyables.ts
> +		aliases: ['Toktz-xil-ul']
aliases everywhere should always be lowercase

2020-09-22 15:27 UTC, gc commented on src/lib/buyables/tokkulBuyables.ts
> +	tokkulCost?: number; // Prices are using the Karamja gloves 1
dont put a comment at the end of the line.
It should be at the top of the like, like this:
```
/**
* Prices are using the Karamja gloves 1
*/
tokkulCost?: number;
```

However, I dont think i want to use karamja gloves prices, considering we might add achievement diaries at some point.

2020-09-22 15:27 UTC, gc commented on src/commands/Minion/tokkulshop.ts
> +					`Cancelling ${type === 'buy' ? 'purcharse' : 'sale'} of **${inItemString}**.`
`purchase`

2020-09-22 15:27 UTC, gc commented on src/commands/Minion/tokkulshop.ts
> +		}
you're throwing this if they have killed jad?

2020-09-27 00:06 UTC, merged