[OSB] Add +autoequip
oldschoolgg/oldschoolbot pull request #711
Opened 2020-09-27 00:56 UTC by kevinsmendes

### Description:

-   Resolves #688 
-   It is now possible to auto equip your best gear automatically depending on your params!
-   Usage: `+autoequip melee|mage|range attack|defence crush|slash|stab|ranged|magic prayer|strength`
-   Prayer and strength and optional. If set, the bot will try to prioritize that over the main stat.
-   Examples:
-- `+autoequip mage attack magic strength` Will prioritize magic strength and magic stat
-- `+autoequip melee defence crush` Willl equip your best defensive crush gear
-- `+autoequip melee attack crush strength` Will equip the best offensive crush gear you have!

### Changes:

-   Adds autoequip

-   [X] I have tested all my changes thoroughly.

2020-09-30 05:40 UTC, gc commented
Are you able to encapsulate this into a standalone function? This is a particular case where I want it done, because the code is quite complex with lots of branches. I'd really like unit tests for it.

2020-09-30 17:16 UTC, kevinsmendes commented
Added unite testings and moved it to its own function

2020-10-03 06:20 UTC, gc requested changes

2020-10-03 06:20 UTC, gc commented on tests/util.getUserBestGearFromBank.test.ts
> +const nulLGear: GearSetup = {
`nulLGear`? typo?

2020-10-03 06:20 UTC, gc commented on tests/util.getUserBestGearFromBank.test.ts
> +		await Items.fetchAll();
use `beforeAll` to do the fetchAll instead of putting it in each test.

2020-10-03 06:20 UTC, gc commented on src/commands/Minion/autoequip.ts
> +		console.log({ toRemoveFromGear, toRemoveFromBank, gearToEquip, userFinalBank });
remove console.log

2020-10-03 06:20 UTC, gc commented on src/lib/minions/functions/getUserBestGearFromBank.ts
> +
Do you need the `?` in `item?` - and maybe this would work more easily: `addArrayOfNumbers(Object.values(item.equipment))`

2020-10-03 06:20 UTC, gc commented on src/lib/minions/functions/getUserBestGearFromBank.ts
> +	userBank: ItemBank,
always always give function's names, and dont export it as default here.

2020-10-11 04:51 UTC, gc commented on tests/util.getUserBestGearFromBank.test.ts
> +				shield: { item: itemID('Dragonfire shield'), quantity: 1 }
you can PR this later, but this would be a lot simpler with the `constructGearSetup` utility I made.

2020-10-11 04:57 UTC, merged