WarriorsguildV2
oldschoolgg/oldschoolbot pull request #788
Opened 2020-10-02 18:59 UTC by Lajnux

### Description:

Removed most unnecessary activities and stuck with main activity.

Now can only do animated armours and cyclops

(Need to fix minigameIDs to make animated armours be tracked and add Cyclops to OldschoolJS)

### Changes:

Removed most unnecessary activities and stuck with main activity.

Now can only do animated armours and cyclops

-   [] I have tested all my changes thoroughly.

2020-10-04 03:30 UTC, kevinsmendes requested changes
You need to add `Activity.Cyclops` and `Activity.AnimatedArmour` to `tickerTaskFromActivity.ts` to allow the user to cancel the trip. Also, would be good to allow the user to not waste time by only thinking they have 1 piece of each armor. The bank is right around the animated armor location and wasting up to 40 minutes because it broke on the first armor will be pissing people off. I recommend you just keep breaking pieces as long the user have them in the bank.

2020-10-04 03:30 UTC, kevinsmendes commented on src/tasks/minions/minigames/warriorsGuild/cyclopsActivity.ts
> +		loot = removeItemFromBank(loot, 19679, user.numItemsInBankSync(196779));
You probably didn't mean itemID 196779

2020-10-04 03:33 UTC, kevinsmendes commented on src/commands/Minion/warriorsguild.ts
> +			if (!bankHasItem(userBank, 8851, 100) && !bankHasItem(userBank, 9747, 1)) {
This should `if (!bankHasItem(userBank, 8851, 100) || !bankHasItem(userBank, 9747, 1)) {`.

2020-12-13 22:27 UTC, closed without merging

2020-12-13 22:27 UTC, Lajnux commented
merged